import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link, Navigate, useParams } from 'react-router-dom'
import gsap from 'gsap'
import { ArrowLeft, ArrowUpRight, Clock, DotsThree, Sparkle, Star } from '@phosphor-icons/react'
import Shell from '../components/Shell'
import { ActionDialog } from '../components/dialogs'
import { iconButton, primaryButton, StatusPill } from '../components/ui'
import { api } from '../mockApi'

function Metric({ label, value, note, last }) { return <div className={`py-3 sm:px-6 ${!last ? 'border-b border-black/[.07] sm:border-b-0 sm:border-r' : ''} first:pl-0`}><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[var(--muted)]">{label}</p><p className="mt-2 text-xl font-semibold tracking-[-.035em]">{value}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{note}</p></div> }

export default function JobDetail() {
  const { id } = useParams(), [dialog, setDialog] = useState(null), root = useRef(null)
  const { data: job, isLoading, isError } = useQuery({ queryKey: ['job', id], queryFn: () => api.getJob(id), retry: false })
  useEffect(() => { if (!job || !root.current) return; const ctx = gsap.context(() => gsap.fromTo('[data-detail]', { y: 24, autoAlpha: 0 }, { y: 0, autoAlpha: 1, duration: .72, stagger: .07, ease: 'power3.out', clearProps: 'opacity,visibility,transform' }), root); return () => ctx.revert() }, [job])
  if (isLoading) return <Shell><div className="grid min-h-[70dvh] place-items-center text-sm text-[var(--muted)]">Opening opportunity…</div></Shell>
  if (isError || !job) return <Navigate to="/jobs" replace />
  return <Shell><main ref={root} className="mx-auto w-full max-w-[1500px] px-4 pb-20 pt-10 sm:px-6 md:pt-14"><div data-detail className="flex items-center justify-between"><Link to="/jobs" className="inline-flex items-center gap-2 text-xs font-bold text-[var(--muted)]"><span className="grid size-9 place-items-center rounded-full bg-black/5"><ArrowLeft size={15} /></span>All opportunities</Link><button className={iconButton}><DotsThree size={20} /></button></div><section className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1.25fr)_minmax(19rem,.75fr)] xl:gap-16"><div><div data-detail className="flex flex-wrap items-center gap-3"><StatusPill status={job.status} /><span className="text-[10px] font-bold uppercase tracking-[.15em] text-[var(--muted)]">Posted {job.posted}</span></div><h1 data-detail className="mt-6 max-w-5xl text-[clamp(3rem,6vw,6.7rem)] font-semibold leading-[.9] tracking-[-.075em]">{job.title}</h1><div data-detail className="mt-8 flex flex-wrap items-center gap-4"><div className="relative size-12 overflow-hidden rounded-2xl bg-[var(--ink)] text-white"><img src={job.image} className="size-full object-cover opacity-70" alt="" /><span className="absolute inset-0 grid place-items-center text-xs font-bold">{job.client}</span></div><div><p className="font-bold">{job.company}</p><p className="mt-1 text-xs text-[var(--muted)]">{job.location}</p></div><div className="ml-2 flex items-center gap-1 rounded-full bg-[var(--lime)]/60 px-3 py-1.5 text-xs font-bold"><Star size={13} weight="fill" />{job.clientStats.rating}</div></div>
      <div data-detail className="mt-12 rounded-[2rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><div className="grid rounded-[calc(2rem-.375rem)] bg-[var(--surface)] p-6 sm:grid-cols-3 sm:p-8"><Metric label="Budget" value={job.budget} note={job.type} /><Metric label="Experience" value={job.level} note={job.duration} /><Metric label="Fit signal" value={`${job.match}%`} note="Strong match" last /></div></div><article data-detail className="py-16"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">The brief</p><p className="mt-7 max-w-3xl text-xl leading-[1.75] tracking-[-.02em] text-[#3f413b] sm:text-2xl">{job.description}</p><div className="mt-8 flex flex-wrap gap-2">{job.tags.map((tag) => <span key={tag} className="rounded-full bg-[var(--surface)] px-4 py-2 text-xs font-semibold ring-1 ring-black/5">{tag}</span>)}</div></article><section data-detail className="border-t border-black/10 py-12"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">Client confidence</p><div className="mt-6 grid grid-cols-3 gap-3">{Object.entries(job.clientStats).map(([key, value]) => <div key={key}><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] capitalize text-[var(--muted)]">{key}</p></div>)}</div></section></div>
      <aside data-detail className="lg:sticky lg:top-28 lg:self-start"><div className="rounded-[2rem] bg-[var(--ink)] p-1.5 text-white"><div className="rounded-[calc(2rem-.375rem)] bg-[#20221d] p-6 sm:p-7"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.2em] text-white/45">Next move</span><Sparkle size={16} /></div><h2 className="mt-6 text-3xl font-semibold leading-tight tracking-[-.05em]">Turn a good fit into a great pitch.</h2><p className="mt-3 text-xs leading-6 text-white/45">Review the tailored letter, make it yours, then log the outcome.</p><button onClick={() => setDialog('apply')} className={`${primaryButton} mt-7 w-full bg-[var(--lime)] text-[var(--ink)]`}><span>Review & apply</span><span className="ml-auto grid size-8 place-items-center rounded-full bg-black/10"><ArrowUpRight size={15} /></span></button><button onClick={() => setDialog('reject')} className="mt-2 w-full rounded-full py-3 text-xs font-bold text-white/50 hover:text-white">Not the right fit</button></div></div><div className="mt-4 rounded-[1.7rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><div className="rounded-[calc(1.7rem-.375rem)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--muted)]">Activity log</p><Clock size={15} /></div><div className="mt-5 space-y-4">{job.activity.map((item, index) => <div key={`${item}-${index}`} className="flex gap-3"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${index === 0 ? 'bg-[var(--lime-dark)]' : 'bg-black/15'}`} /><div><p className="text-xs font-medium leading-5">{item}</p><p className="mt-1 text-[9px] text-[var(--muted)]">{index === 0 ? 'Latest' : `${index + 1} events ago`}</p></div></div>)}</div></div></div></aside></section>{dialog && <ActionDialog type={dialog} job={job} onClose={() => setDialog(null)} />}</main></Shell>
}
