import { useMemo, useState } from 'react'
import { Check, FloppyDisk, Target } from '@phosphor-icons/react'
import Shell from '../components/Shell'
import { primaryButton } from '../components/ui'
import { loadPreferences, savePreferences } from '../lib/preferences'
import { seedJobs } from '../data'

export default function Preferences() {
  const [form, setForm] = useState(loadPreferences)
  const [saved, setSaved] = useState(false)
  const skills = useMemo(() => [...new Set(seedJobs.flatMap((job) => job.tags))].sort(), [])
  const toggle = (skill) => setForm((current) => ({ ...current, skills: current.skills.includes(skill) ? current.skills.filter((item) => item !== skill) : [...current.skills, skill] }))
  const submit = (event) => { event.preventDefault(); savePreferences(form); setSaved(true); setTimeout(() => setSaved(false), 1800) }
  return <Shell><main className="mx-auto w-full max-w-[1100px] px-4 pb-24 pt-14 sm:px-6 md:pt-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">Scoring preferences</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.065em] sm:text-7xl">Define your <span className="font-serif italic">best fit.</span></h1></div><p className="max-w-xs text-sm leading-6 text-[var(--muted)]">These preferences directly influence every opportunity’s explainable score.</p></div><form onSubmit={submit} className="mt-14 grid gap-5 md:grid-cols-2"><section className="rounded-[2rem] bg-black/[.045] p-1.5 ring-1 ring-black/5 md:col-span-2"><div className="rounded-[calc(2rem-.375rem)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--lime)] text-[#26320b]"><Target size={18} /></span><div><h2 className="text-lg font-semibold">Preferred skills</h2><p className="text-[10px] text-[var(--muted)]">Select every skill you confidently sell.</p></div></div><div className="mt-6 flex flex-wrap gap-2">{skills.map((skill) => <button type="button" key={skill} onClick={() => toggle(skill)} className={`rounded-full px-4 py-2 text-xs font-semibold ring-1 transition-all duration-500 ${form.skills.includes(skill) ? 'bg-[var(--lime)] !text-[#26320b] ring-[var(--lime-dark)]/30' : 'bg-[var(--paper)] text-[var(--muted)] ring-black/5'}`}>{skill}{form.skills.includes(skill) && <Check size={12} className="ml-1.5 inline" />}</button>)}</div></div></section>
    <PreferenceField label="Minimum fixed project" prefix="$" value={form.minimumFixedBudget} onChange={(value) => setForm({ ...form, minimumFixedBudget: Number(value) })} /><PreferenceField label="Minimum hourly rate" prefix="$" suffix="/hr" value={form.minimumHourlyRate} onChange={(value) => setForm({ ...form, minimumHourlyRate: Number(value) })} /><section className="rounded-[1.8rem] bg-black/[.045] p-1.5 ring-1 ring-black/5 md:col-span-2"><div className="rounded-[calc(1.8rem-.375rem)] bg-[var(--surface)] p-6"><label className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--muted)]">Blocked keywords</label><input value={form.blockedKeywords.join(', ')} onChange={(event) => setForm({ ...form, blockedKeywords: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} className="mt-3 w-full rounded-2xl bg-[var(--paper)] px-4 py-3.5 text-sm outline-none ring-1 ring-black/5 focus:ring-[var(--lime-dark)]" /><p className="mt-2 text-[10px] text-[var(--muted)]">Comma-separated phrases that should lower an opportunity’s priority.</p></div></section><div className="flex justify-end md:col-span-2"><button className={`${primaryButton} min-w-48`}><span>{saved ? 'Preferences saved' : 'Save preferences'}</span><span className="grid size-8 place-items-center rounded-full bg-white/10">{saved ? <Check size={15} /> : <FloppyDisk size={15} />}</span></button></div></form></main></Shell>
}

function PreferenceField({ label, prefix, suffix, value, onChange }) { return <section className="rounded-[1.8rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><div className="rounded-[calc(1.8rem-.375rem)] bg-[var(--surface)] p-6"><label className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--muted)]">{label}</label><div className="mt-5 flex items-baseline gap-2"><span className="text-xl text-[var(--muted)]">{prefix}</span><input type="number" min="0" value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 bg-transparent text-4xl font-semibold tracking-[-.05em] outline-none" /><span className="text-xs text-[var(--muted)]">{suffix}</span></div></div></section> }
