import { useNavigate } from 'react-router-dom'
import { useQueryClient } from '@tanstack/react-query'
import { Briefcase, EnvelopeSimple, MapPin, SignOut, Star } from '@phosphor-icons/react'
import Shell from '../components/Shell'
import { primaryButton } from '../components/ui'
import { clearSession, getSessionUser, userInitials } from '../lib/auth'

export default function Profile() {
  const navigate = useNavigate(), queryClient = useQueryClient()
  const user = getSessionUser()
  const logout = () => { queryClient.clear(); clearSession(); navigate('/login', { replace: true }) }
  return <Shell><main className="mx-auto w-full max-w-[1100px] px-4 pb-24 pt-14 sm:px-6 md:pt-20"><div className="rounded-[2.3rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><section className="relative overflow-hidden rounded-[calc(2.3rem-.375rem)] bg-[var(--surface)] p-6 sm:p-10"><div className="absolute right-0 top-0 h-56 w-72 bg-[var(--lime)]/20 blur-[90px]" /><div className="relative flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><div className="grid size-24 place-items-center rounded-[2rem] bg-[var(--ink)] text-2xl font-bold text-white shadow-[0_20px_50px_rgba(20,22,18,.2)]">{userInitials(user?.name)}</div><p className="mt-7 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">Independent professional</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.065em] sm:text-7xl">{user?.name}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--muted)]">Product designer and React specialist crafting considered digital products for ambitious teams.</p></div><button onClick={logout} className={`${primaryButton} self-start bg-[#f5d6cf] text-[var(--danger)] md:self-auto`}><span>Log out</span><span className="grid size-8 place-items-center rounded-full bg-white/45"><SignOut size={15} /></span></button></div></section></div>
    <section className="mt-5 grid gap-5 md:grid-cols-[1fr_.8fr]"><div className="rounded-[1.8rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><div className="h-full rounded-[calc(1.8rem-.375rem)] bg-[var(--surface)] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">Account</p><div className="mt-7 space-y-5">{[[EnvelopeSimple, 'Email', user?.email], [MapPin, 'Location', 'India · GMT +5:30'], [Briefcase, 'Workspace', 'Pitchflow Studio']].map(([Icon, label, value]) => <div key={label} className="flex items-center gap-4"><span className="grid size-10 place-items-center rounded-xl bg-[var(--paper)]"><Icon size={17} /></span><div><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[var(--muted)]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div></div>)}</div></div></div><div className="rounded-[1.8rem] bg-[var(--ink)] p-1.5 text-white"><div className="h-full rounded-[calc(1.8rem-.375rem)] bg-[#20221d] p-6 sm:p-8"><Star size={22} className="text-[var(--lime)]" weight="fill" /><p className="mt-8 text-[10px] font-bold uppercase tracking-[.2em] text-white/40">Profile strength</p><p className="mt-3 text-5xl font-semibold tracking-[-.06em]">92%</p><p className="mt-4 text-xs leading-6 text-white/45">Your profile is ready for high-fit opportunities. Add two recent case studies to complete it.</p></div></div></section></main></Shell>
}
