import { CheckCircle, Sparkle, WarningCircle } from '@phosphor-icons/react'
import { scoreJob } from '../lib/scoring'

export default function ScoreBreakdown({ job }) {
  const fit = scoreJob(job)
  return <section className="rounded-[2rem] bg-black/[.045] p-1.5 ring-1 ring-black/5"><div className="rounded-[calc(2rem-.375rem)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]"><Sparkle size={14} />Explainable fit score</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em]">{fit.verdict}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--muted)]">Calculated from your preferred skills, target rate, client quality, experience level, and how recently the job was posted.</p></div><div className="flex size-24 shrink-0 flex-col items-center justify-center rounded-full bg-[var(--lime)] text-[#26320b] ring-8 ring-[var(--lime)]/20"><span className="text-3xl font-bold tracking-[-.06em]">{fit.score}</span><span className="text-[8px] font-bold uppercase tracking-[.12em]">out of 100</span></div></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-2">{fit.factors.map((factor) => <div key={factor.label} className="rounded-2xl bg-[var(--paper)] p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold">{factor.label}</span><span className="text-[10px] font-bold text-[var(--muted)]">{factor.points}/{factor.max}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-black/[.07]"><div style={{ transform: `scaleX(${factor.points / factor.max})` }} className={`h-full origin-left rounded-full ${factor.tone === 'warning' ? 'bg-[var(--danger)]' : factor.tone === 'positive' ? 'bg-[var(--lime-dark)]' : 'bg-[var(--lavender)]'}`} /></div><p className="mt-3 text-[10px] leading-4 text-[var(--muted)]">{factor.detail}</p></div>)}</div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#e8f2d0] p-4 text-[#34420f]"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em]"><CheckCircle size={15} weight="fill" />Why it works</div><p className="mt-2 text-xs leading-5">{fit.positives[0] || 'The opportunity meets your baseline preferences.'}</p></div><div className={`rounded-2xl p-4 ${fit.concerns.length ? 'bg-[#f5d6cf] text-[#762f25]' : 'bg-[var(--paper)] text-[var(--muted)]'}`}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em]"><WarningCircle size={15} weight="fill" />Watch for</div><p className="mt-2 text-xs leading-5">{fit.concerns[0] || 'No major concerns detected from the available data.'}</p></div></div>
  </div></section>
}
