const now = Date.now()

export const seedJobs = [
  {
    id: 'nora',
    title: 'Senior Product Designer for AI workspace',
    company: 'Nora Labs',
    client: 'ML',
    location: 'San Francisco, CA',
    posted: '18 min ago',
    postedAt: new Date(now - 18 * 60 * 1000).toISOString(),
    budget: '$8k–$12k',
    type: 'Fixed price',
    level: 'Expert',
    duration: '1–3 months',
    status: 'New',
    match: 96,
    tags: ['Product design', 'Figma', 'Design systems'],
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=85',
    url: 'https://upwork.com/jobs/~01nora-ai-product?utm_source=feed',
    description: 'We are building a calm, intelligent workspace for teams working with large language models. We need a senior product designer to shape the core experience—from research synthesis to a production-ready design system.',
    clientStats: { spent: '$240k+', hires: '38 hires', rating: '4.98' },
    activity: ['Job imported from saved search', 'Duplicate URL check passed'],
  },
  {
    id: 'northstar',
    title: 'React developer for premium travel platform',
    company: 'Northstar Travel',
    client: 'NS',
    location: 'London, UK',
    posted: '1 hr ago',
    postedAt: new Date(now - 60 * 60 * 1000).toISOString(),
    budget: '$65–$90/hr',
    type: 'Hourly',
    level: 'Expert',
    duration: '3–6 months',
    status: 'New',
    match: 92,
    tags: ['React', 'TypeScript', 'GSAP', 'QA'],
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=85',
    url: 'https://upwork.com/jobs/~01northstar-react',
    description: 'Northstar is reimagining high-touch trip planning. Join a small senior team to build the new customer journey in React, with an emphasis on beautiful motion, thoughtful accessibility, and frontend performance.',
    clientStats: { spent: '$91k+', hires: '17 hires', rating: '5.0' },
    activity: ['Job imported from direct link', 'Duplicate URL check passed'],
  },
  {
    id: 'kinetic',
    title: 'Brand identity & web direction for fintech',
    company: 'Kinetic Finance',
    client: 'KF',
    location: 'Toronto, CA',
    posted: 'Yesterday',
    postedAt: new Date(now - 24 * 60 * 60 * 1000).toISOString(),
    budget: '$5,500',
    type: 'Fixed price',
    level: 'Intermediate',
    duration: '1–3 months',
    status: 'Applied',
    match: 88,
    tags: ['Branding', 'Web design', 'SEO'],
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85',
    url: 'https://upwork.com/jobs/~01kinetic-brand',
    description: 'We need an identity refresh and digital direction that feels confident, credible, and deeply human. The engagement includes a sharpened visual language, a marketing site direction, and a scalable design toolkit.',
    clientStats: { spent: '$54k+', hires: '12 hires', rating: '4.92' },
    activity: ['Job imported from Upwork', 'Status changed from New to Applied', 'Cover letter saved and application logged'],
  },
  {
    id: 'arc',
    title: 'UX audit for B2B analytics dashboard',
    company: 'Arc Metrics',
    client: 'AM',
    location: 'Berlin, DE',
    posted: '2 days ago',
    postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    budget: '$2,400',
    type: 'Fixed price',
    level: 'Intermediate',
    duration: 'Less than 1 month',
    status: 'Rejected',
    reason: 'Budget is below our minimum project threshold.',
    match: 71,
    tags: ['UX audit', 'B2B', 'Analytics'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85',
    url: 'https://upwork.com/jobs/~01arc-ux',
    description: 'Audit our analytics product and identify the highest-impact improvements for onboarding, navigation, and reporting workflows.',
    clientStats: { spent: '$11k+', hires: '8 hires', rating: '4.81' },
    activity: ['Job imported from saved search', 'Status changed from New to Rejected', 'Reason: Budget below threshold'],
  },
]

export const coverLetterTemplate = `Hi there,\n\nYour vision for {company} immediately stood out—especially the opportunity to bring clarity and craft to a complex product. I’ve led similar engagements where thoughtful systems and a polished execution materially improved both customer confidence and team velocity.\n\nI’d begin with a focused discovery session, map the critical journey, and move quickly into a tangible direction your team can react to. You’ll get clear communication, senior-level thinking, and production-minded work throughout.\n\nI’d love to share a few relevant examples and hear more about what success looks like for you.\n\nBest,\nWaseem`
